name: Run EMCL DividendHistory.org Only Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-emcl-divhist-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml requests

      - name: Run EMCL DividendHistory.org only scraper
        run: |
          python dividendhistory_only_scraper.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dividendhistory_emcl_only.csv
          git commit -m "Update EMCL DividendHistory.org only data" || true
          git push
