# .github/workflows/emcl_dividends_dho.yml
name: EMCL DividendHistory.org Scrape (single-ticker)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml pandas

      - name: Run scraper
        run: |
          python emcl_dividends_dho.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add emcl_dividends_dho.csv
          git commit -m "Update EMCL dividendhistory.org data" || echo "No changes to commit"
          git push
