name: Run EMCL DividendHistory.org Only Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-emcl-divhist-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas playwright
          playwright install chromium

      - name: Run EMCL DividendHistory.org only scraper
        run: python emcl_dividends_dho.py

      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "emcl_dividends_dho.csv" ]; then
            git add emcl_dividends_dho.csv
            git commit -m "Update EMCL DividendHistory.org only data" || echo "Nothing to commit"
            git push
          else
            echo "⚠️ No CSV file to commit"
