name: Run EMCL DividendHistory.org Scraper

on:
  workflow_dispatch:  # Manual run

permissions:
  contents: write

jobs:
  run-emcl-dho:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas playwright
          playwright install --with-deps chromium

      - name: Run EMCL scraper
        run: python emcl_dividends_dho.py

      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add emcl_dividends_dho.csv
          git commit -m "Update EMCL DividendHistory.org data" || echo "Nothing to commit"
          git push
