name: Run Historical ETF Yield Tracker

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python historical_yield_tracker.py

      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add historical_yield_*.csv
          git commit -m "Auto-update historical yield data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
