name: Run Historical Yield Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 06:00 UTC

permissions:
  contents: write

jobs:
  run-historical:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas yfinance lxml requests

      - name: Run historical tracker script
        run: python historical_yield_tracker.py

      - name: Commit and push new/updated CSVs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update historical yield data (weekly run)" || echo "Nothing to commit"
          git push
