name: Fix Frequency + Recalculate Yields

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch-and-recalc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas

      - name: Run frequency fix + yield recalculation
        run: |
          python frequency_inference.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git status
          git commit -m "Update yield stats (median/mean columns)" || echo "No changes to commit"
          git push
